version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: twilio
    versions:
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: alembic
    versions:
    - 1.5.6
    - 1.5.7
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pyjwt
    versions:
    - 2.0.1
  - dependency-name: coverage
    versions:
    - "5.4"
    - "5.5"
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
  - dependency-name: httplib2
    versions:
    - 0.18.0
    - 0.19.0
  - dependency-name: snowballstemmer
    versions:
    - 2.1.0
  - dependency-name: pygments
    versions:
    - 2.7.4
  - dependency-name: babel
    versions:
    - 2.9.0
  - dependency-name: flask
    versions:
    - "1.0"
  - dependency-name: werkzeug
    versions:
    - 0.15.3
  - dependency-name: alabaster
    versions:
    - 0.7.12
  - dependency-name: jinja2
    versions:
    - 2.10.1
